import React, { useState } from 'react'
import styles from "./styles.module.css"
import markerIcon from '@/public/icons/marker.svg'
import Image from 'next/image'
import { useForm } from 'react-hook-form'
import { MultiSelect, useMultiSelect } from 'chakra-multiselect'
import { Button } from '@chakra-ui/react'

const DEFAULT_VALUES = [
    { label: "Cheap", value: "cheap" },
    { label: "Worst", value: "worst" },
    { label: "Free", value: "free" }
]

function Pill({ text }) {
    return (
        <div className={styles.pill}>
            {text}
        </div>
    )
}

function NegativeKeywords() {
    const [mode, setMode] = useState("display")

    const {
        register,
        handleSubmit,
        setValue,
        watch,
    } = useForm({
        defaultValues: {
            keywords: DEFAULT_VALUES,
        }
    })

    const { value: selectedValues, options, onChange } = useMultiSelect({
        value: DEFAULT_VALUES,
        options: []
    })

    const handleCancel = () => {
        setMode("display")
    }

    const onSubmit = (data) => {
        setValue("keywords", selectedValues)
        setMode("display")
    }

    return (
        <div className={styles.negative_words}>
            <h3 className={styles.negative_heading}>
                NEGATIVE KEYWORDS
            </h3>
            <p className={styles.negative_subheading}>
                These words will never be part of content generated by Fibr
            </p>

            {mode === "display" ? (
                <div className={styles.keyword_pills}>
                    {watch("keywords").map(val => {
                        return <Pill text={val.value} />
                    })}
                </div>
            ) : (
                <form
                    className={styles.negative_keywords_form}
                    onSubmit={handleSubmit(onSubmit)}
                >
                    <MultiSelect
                        options={options}
                        value={selectedValues}
                        onChange={onChange}
                        create
                        className={styles.multi_select}
                    />
                    <div className={styles.form_actions}>
                        <Button
                            colorScheme='#667bf6;'
                            variant='link'
                            onClick={handleCancel}
                        >
                            Cancel
                        </Button>
                        <Button
                            colorScheme='#667bf6;'
                            variant='solid'
                            type='submit'
                        >
                            Save
                        </Button>
                    </div>
                </form>
            )}

            <div
                className={styles.edit_control}
                onClick={() => { setMode("edit") }}
            >
                <span className={styles.edit_icon_container}>
                    <Image
                        className={styles.edit_icon}
                        src={markerIcon}
                        width={13}
                        height={13}
                    />
                </span>
                <span>Edit</span>
            </div>
        </div>
    )
}

export default NegativeKeywords
